[phases.setup]
nixPkgs = ["dotnet-sdk_8", "nodejs_18", "npm"]

[phases.install]
cmds = [
  "cd questionnaire.client && npm install",
  "cd questionnaire.client && npm run build",
  "dotnet restore Questionnaire.Server/Questionnaire.Server.csproj"
]

[phases.build]
cmds = ["dotnet publish Questionnaire.Server/Questionnaire.Server.csproj --no-restore -c Release -o out"]

[start]
cmd = "dotnet out/Questionnaire.Server.dll"
